kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: boissibook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boissibook
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80