name: Cloud Build deploy on dev
on:
  push:
    branches:
      - dev

jobs:
  test-deploy:
    name: Run tests then deploy
    runs-on: ubuntu-latest

    steps:
      - name: Pull project
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run mvn test
        run: mvn --batch-mode --update-snapshots test
      - name: Trigger cloud build deployment
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.WEBHOOK_URL }}