name: Docker image build and push
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nospy/boissibook:latest
  gcp-build:
    name: Build and push Docker images to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: boissibook
      IMAGE_TAG: latest
      GCP_PROJECT_ID: boissibook
      GCP_REGISTRY_URL: europe-west9-docker.pkg.dev
      GCP_REGISTRY_NAME: boissi-registry
    steps:
      - uses: actions/checkout@v2

      - name: Auth to Gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker Image to GCR
        run: |-
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.GCP_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.GCP_REGISTRY_URL }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}